### ISSUE TITLE
captured values don't live long enough when passing to sub-components after upgrading to 0.6.1

### ISSUE THREAD

**Issue by jonner** [tokio-rs/topcoat#358]
After the changes in 0.6.x, I'm now getting lifetime errors within a view telling me that arguments are not living long enough after being captured by a coroutine:

```
error[E0597]: `status` does not live long enough
   --> web/src/components.rs:360:52
    |
353 | /     view! {
354 | |         <div>
355 | |             for item in items {
356 | |                 <div>
...   |
359 | |                             if let Some(status) = item.user_status {
    | |                                         ------ binding `status` declared here
360 | |                                 badge_test(status: status)
    | |                                                    ^^^^^^ borrowed value does not live long enough
...   |
368 | |         </div>
369 | |     }
    | |     -
    | |     |
    | |_____`status` dropped here while still borrowed
    |       value captured here by coroutine
```

Minimal reproducer:
```rust
#[derive(Debug, Clone, Copy)]
pub enum Status {
    First,
    Second,
}

pub struct Obj {
    name: String,
    user_status: Option<Status>,
    post_status: Option<Status>,
}

#[component]
pub async fn test(items: &[&Obj]) -> topcoat::Result {
    view! {
        <div>
            for item in items {
                <div>
                    <span>(&item.name)</span>
                    <div>
                        if let Some(status) = item.user_status {
                            badge_test(status: status)
                        }
                        if let Some(status) = item.post_status {
                            badge_test(status: status)
                        }
                    </div>
                </div>
            }
        </div>
    }
}

#[component]
pub async fn badge_test(status: Status, #[default] mut attrs: Attributes) -> topcoat::Result {
    let (klass, text) = match status {
        Status::First => ("first", "First"),
        Status::Second => ("second", "Second"),
    };
    view! {
        <div class=(class!(klass, "badge", attrs.remove("class"))) (attrs)>(text)</div>
    }
}

```

Note that if I only have one of those `if let Some(status)...` blocks, I get no errors, but if I have both of them, I get lifetime errors for both sub-component call sites. Cloning the status variable doesn't seem to make any difference, and it's hard to know what's happening in the background within the view! macro to know what might be going wrong.

**Comment by pikaju** [comment]
Thank you for reporting! This should be fixed by #360

**Comment by pikaju** [comment]
Shipped in 0.6.2

**Comment by jonner** [comment]
Thanks for the quick response. Re: the commit message, can you clarify what 'mutations' you are discouraging that exist in the reproducer?

**Comment by pikaju** [comment]
@jonner that wasn't related to your code, I just meant that I want to ship this as a minor version despite it being technically breaking. 

What I mean is that topcoat discourages mutating your values in your `view!`, e.g. you could do something like this:
```rust
let mut i = 0;
view! {
  <input value=({ i += 1; i })>
  <input value=({ i += 1; i })>
  <input value=({ i += 1; i })>
}
```
which would probably compile, but you're not supposed to depend on the order of operations here, simply because it's difficult to reason about. Especially now that we have concurrent rendering, the order components are run in is unpredictable. So it's a good practice to keep your inputs to the `view!` as immutable. I hope that makes sense.
